### ISSUE TITLE
Login process

### ISSUE THREAD

**Issue by AFAgarap** [jmebia/barangay696-CBIS#2]
@jmebia How about passing the username and password as parameters in your handleLoginButton()? Yes, a "username". Though I know you are quite aware of it, just a friendly reminder, you know. The username is the basis of the level of control of each user in the system.

Furthermore, if the username and password shall be parameters, line 40 would be `if (password.equals("<password>"))` instead, right? Remember functional programming paradigm? So, handleLoginButton() shall return a value that will be the basis of whether the login is successful or not.

Sorry for meddling, just giving some unsolicited advices.

**Comment by jmebia** [comment]
@AFAgarap I have added some model classes that will handle the login process. Thanks.

**Comment by AFAgarap** [comment]
Seems good. :+1:
